name: build_and_test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        ports:
          - 54321:5432
        # healtcheck
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Remove existing go.mod
      run: rm -f go.mod go.sum

    - name: Set up Go
      uses: actions/setup-go@v4
      id: setup_go
      with:
        go-version: '1.20'
    
    - name: Initialize Go module
      run: |
        go mod init github.com/go_backed_misc
        go get github.com/lib/pq
        go mod tidy

    - name: Install golang-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.12.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate.linux-amd64 /usr/local/bin/migrate
        which migrate
      
    - name: Run migrations
      run: make migrate_up

    - name: Test
      run: make test
